config/routes.rb
Demo::Application.routes.draw do

  resources :projects do
    collection do
      get  'import_file'
      post 'import'
      post 'search'
    end
  end

end

app/models/project.rb
#encoding: utf-8
class Project < ActiveRecord::Base
  attr_protected :project_number_id
  belongs_to :project_number

  PUBLISH_STATUS_PUBLISHED = 1 
  PUBLISH_STATUS_DELETED   = 2
  PUBLISH_STATUS_INVALID   = 3

  PUBLISH_STATUS_ARRAY = [["发布", PUBLISH_STATUS_PUBLISHED],
                          ["删除", PUBLISH_STATUS_DELETED],
                          ["无效", PUBLISH_STATUS_INVALID]] 

  scope :published, :conditions => { :publish_status => PUBLISH_STATUS_PUBLISHED }

  def published?
    self.publish_status == PUBLISH_STATUS_PUBLISHED
  end
  
  def invalid?
    self.publish_status == PUBLISH_STATUS_INVALID
  end

  class << self

    def save_project_from_external(row, number)
      name = row[1]
      project_number  = ProjectNumber.find_by_number(number)
      if project_number && name.present?
        project = assemble_data_from_row(row)
        project.project_number = project_number
        project.publish_status = PUBLISH_STATUS_PUBLISHED
        project.save
      else
        project = assemble_data_from_row(row) 
        project.publish_status = PUBLISH_STATUS_INVALID
        project.save
      end
      project
    end

    def assemble_data_from_row(row)
      project = Project.new
      project.name                  = row[1]
      project.unit                  = row[2]
      project.contact_count         = row[3]
      project.unit_price            = row[4]
      project.prior_project_count   = row[5]
      project.prior_price           = row[6]
      project.current_project_count = row[7]
      project.current_price         = row[8]
      project.project_count         = row[9]
      project.project_price         = row[10]
      project.comment               = row[11]
      project
    end

  end
end

app/models/project_number.rb
class ProjectNumber < ActiveRecord::Base
  attr_accessible :number
  has_many :projects

end

app/controllers/application_controller.rb
#encoding: utf-8
require 'roo'
class ApplicationController < ActionController::Base
  protect_from_forgery

  START_COLUMN_NUMBER = 4

  def import_excle(file)
    result = { status: true, valid_project: [], invalid_project: [] }
    spreadsheet = open_spreadsheet(file)
    return if spreadsheet == false

    (START_COLUMN_NUMBER..spreadsheet.last_row).each do |i|
      if valid_row?(spreadsheet.row(i))
        number  = format_project_number(spreadsheet.cell(i,'A'))
        project = Project.save_project_from_external(spreadsheet.row(i), number)
        project.published? ? result[:valid_project] << project : result[:invalid_project] << project
      end
    end
    result[:invalid_project].reject!{|project| project.name.blank? }
    result
  end

  private

  def format_project_number(number)
    number.kind_of?(Float) ? number.to_i.to_s : number
  end

  def valid_row?(row)
    row[0].present? || row[1].present?
  end

  def open_spreadsheet(file)
    return false  if file.blank?
    case File.extname(file.original_filename)
    when ".csv"  then Roo::Csv.new(file.path, nil, :ignore)
    when ".xls"  then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else 
      false
    end
  end

end

app/controllers/projects_controller.rb
#encoding: utf-8
class ProjectsController < ApplicationController

  def index
    @projects = Project.published
  end

  def search
    status = params[:publish_status]
    status.blank? ? @notice = "请选择状态" : @projects = Project.where(publish_status: status)
    render "index"
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    project = Project.find(params[:id])
    Project.update(project.id, params[:project])
    redirect_to project_url(project)
  end

  def destroy
    project = Project.find(params[:id])
    project.update_attributes(publish_status: Project::PUBLISH_STATUS_DELETED)
    redirect_to :action => "index"
  end

  def import
    result = import_excle(params[:file])
    if result.blank?
      flash[:notice] = "上传文件失败,请检查文件格式,只支持csv,xls,xlsx格式"
      redirect_to import_file_projects_url
    else
      @valid_projects   = result[:valid_project]
      @invalid_projects = result[:invalid_project]
      @notice = "注意:红色区域是不合法数据,请及时按格式修改!"  if @invalid_projects.present?
      render "import_success"
    end
  end

end

app/helpers/application_helper.rb
#encoding: utf-8
module ApplicationHelper

  def display_publish_status(project)
    case project.publish_status
    when Project::PUBLISH_STATUS_PUBLISHED
      "发布"
    when Project::PUBLISH_STATUS_DELETED
      "删除"
    else
      "无效"
    end
  end

  def publish_status_options(selected = nil)
    options = [["请选择状态",nil]]
    options += Project::PUBLISH_STATUS_ARRAY
    options_for_select(options, selected)
  end

end

app/helpers/project_helper.rb
#encoding: utf-8
module ProjectHelper

  def display_class_of_project(project)
    project.invalid? ? "error" : ""
  end

  def project_number_options(selected = nil)
    options = [["请选择编号",nil]]
    options += ProjectNumber.all.collect{|p| [p.number, p.id] }
    options_for_select(options, selected)
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_column_title.html.erb
<thead>
  <tr>
    <th>ID</th>
    <th>项目编号</th>
    <th>项目名称</th>
    <th>单位</th>
    <th>合同价</th>
    <th>单价</th>
    <th>至上期累计结算(工程量)</th>
    <th>至上期累计结算(合价)</th>
    <th>本期结算(工程量)</th>
    <th>本期结算(合价)</th>
    <th>至本期累计结算(工程量)</th>
    <th>至本期累计结算(合价)</th>
    <th>备注</th>
    <th>创建时间</th>
    <th>状态</th>
    <th>操作</th>
  </tr>
</thead>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label "项目编号", :class => 'control-label' %>
    <div class="controls">
      <%= select_tag "people", project_number_options(@project.project_number_id) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "项目名称", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "单位", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :unit, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "单价", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :unit_price, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "至上期累计结算(工程量)", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :prior_project_count, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "至上期累计结算(合价)", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :prior_price, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "本期结算(工程量)", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :current_project_count, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "本期结算(合价)", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :current_price, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "至本期累计结算(工程量)", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :project_count, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "至本期累计结算(合价)", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :project_price, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "备注", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :comment, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "发布状态", :class => 'control-label' %>
    <div class="controls">
      <%= select_tag "publish_status", publish_status_options(@project.publish_status) %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/_notice_msg.erb
<% if flash[:notice].present? || @notice.present? %>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Warning!</strong> <%= flash[:notice]%>
    <strong>Warning!</strong> <%= @notice %>
  </div>
<% end %>

app/views/projects/_projects.html.erb
<tbody>
  <% projects && projects.each do |project| %>
    <tr class=<%= display_class_of_project(project)%>>
      <td><%= link_to project.id, project_path(project) %></td>
      <td><%= project.project_number.try(:number) %></td>
      <td><%= project.name %></td>
      <td><%= project.unit %></td>
      <td><%= project.contact_count %></td>
      <td><%= project.unit_price %></td>
      <td><%= project.prior_project_count %></td>
      <td><%= project.prior_price %></td>
      <td><%= project.current_project_count %></td>
      <td><%= project.current_price %></td>
      <td><%= project.project_count %></td>
      <td><%= project.project_price %></td>
      <td><%= project.comment %></td>
      <td><%= project.created_at.to_s(:db) %></td>
      <td><%= display_publish_status(project)%></td>
      <td>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
          edit_project_path(project), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            project_path(project),
            :method => :delete,
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-mini btn-danger' %>
          </td>
    </tr>
  <% end %>
</tbody>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/import_file.html.erb
<h2>上传文件</h2>
<%= render partial: "notice_msg" %>
<div class="well">
  <%= form_tag import_projects_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import", :class => "btn btn-primary" %>
  <% end %>
</div>

app/views/projects/import_success.html.erb
<div class="page-header">
  <%= render partial: "notice_msg" %>
  <a href="<%= projects_path %>" class="btn btn-large btn-primary disabled">返回列表页面</a>
</div>
<table class="table table-bordered">
  <%= render partial: "column_title" %>
  <%= render partial: "projects",   :locals => { projects: @valid_projects } %>
  <%= render partial: "projects",   :locals => { projects: @invalid_projects } %>
</table>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <%= render partial: "notice_msg" %>
</div>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <%= link_to "上传文件", import_file_projects_path, :class => 'btn btn-primary' %>
  <%= form_tag search_projects_path, multipart: true do %>
    <%= select_tag "publish_status",  publish_status_options %>
    <%= submit_tag "查询", :class => "icon-search" %>
  <% end %>
</div>

<% if @projects.present? %>
  <table class="table table-striped">
    <%= render partial: "column_title" %>
    <%= render partial: "projects",   :locals => { projects: @projects } %>
  </table>
<% else %>
  <div class="well">
    暂无数据
  </div>
<% end %>

<%= link_to "新建", new_project_path, :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>项目编号</strong></dt>
  <dd><%= @project.project_number.try(:number) %></dd>
  <dt><strong>项目名称</strong></dt>
  <dd><%= @project.name %></dd>
  <dt><strong>单位</strong></dt>
  <dd><%= @project.unit %></dd>
  <dt><strong>单价</strong></dt>
  <dd><%= @project.unit_price %></dd>
  <dt><strong>至上期累计结算(合价)</strong></dt>
  <dd><%= @project.prior_price %></dd>
  <dt><strong>至上期累计结算(工程量)</strong></dt>
  <dd><%= @project.prior_project_count %></dd>
  <dt><strong>本期结算(合价)</strong></dt>
  <dd><%= @project.current_price %></dd>
  <dt><strong>本期结算(工程量)</strong></dt>
  <dd><%= @project.current_project_count %></dd>
  <dt><strong>至本期累计结算(合价)</strong></dt>
  <dd><%= @project.project_price %></dd>
  <dt><strong>至本期累计结算(工程量)</strong></dt>
  <dd><%= @project.project_count %></dd>
  <dt><strong>备注</strong></dt>
  <dd><%= @project.comment %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_path(@project), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_path(@project),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>